title: Open Source Demo Docs
description: "Sample for getting started with documentation for an open source package"
remote_theme: just-the-docs/just-the-docs
color_scheme: "dim"
search_enabled: true
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

defaults:
-
  scope: 
    path: "decisions"
  values:
    layout: "adr"
    parent: "Architecture Decision Records"
    hideTitle: true